# Generated by Django 5.2.5 on 2025-08-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theuser',
            name='role',
            field=models.CharField(choices=[('staff_1', 'Staff'), ('client_1', 'Client')], max_length=20),
        ),
    ]
